IF OBJECT_ID('dbo.SYSBENUTZER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SYSBENUTZER (
        BENID NVARCHAR(100) NOT NULL PRIMARY KEY,
        BENADUID NVARCHAR(100) NOT NULL,
        BENSASXUSER NVARCHAR(100) NOT NULL,
        BENVORNAME NVARCHAR(100) NULL,
        BENNACHNAME NVARCHAR(100) NULL,
        BENKUERZEL NVARCHAR(20) NULL,
        BENMAIL NVARCHAR(255) NULL,
        BENANZEIGENAME NVARCHAR(255) NULL,
        BENAKTUALISIERTAM DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );
END;
GO

IF OBJECT_ID('dbo.DATSCHADENSFAELLE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DATSCHADENSFAELLE (
        SFAID NVARCHAR(80) NOT NULL PRIMARY KEY,
        SFANUMMER NVARCHAR(20) NOT NULL,
        SFAGILTAB NVARCHAR(8) NOT NULL,
        SFAGILTBIS NVARCHAR(8) NOT NULL DEFAULT '99999999',
        SFADELDAT NVARCHAR(14) NULL,
        SFASTATUS NVARCHAR(50) NOT NULL DEFAULT 'Neu',
        SFABETREFF NVARCHAR(255) NULL,
        SFABEZEICHNUNG NVARCHAR(255) NULL,
        SFADATUM NVARCHAR(10) NULL,
        SFABESCHREIBUNG NVARCHAR(MAX) NULL,
        SFASTRASSE NVARCHAR(120) NULL,
        SFAABSCHNITTVON NVARCHAR(50) NULL,
        SFAABSCHNITTBIS NVARCHAR(50) NULL,
        SFARICHTUNG NVARCHAR(120) NULL,
        SFAKMSTATION NVARCHAR(30) NULL,
        SFALANDKREIS NVARCHAR(120) NULL,
        SFAKENNZEICHEN NVARCHAR(30) NULL,
        SFAZULASSUNGSSTELLE NVARCHAR(120) NULL,
        SFAVERURSACHER NVARCHAR(255) NULL,
        SFAVERSICHERUNG NVARCHAR(255) NULL,
        SFAVERSICHERUNGSSCHEINNR NVARCHAR(100) NULL,
        SFAVERSICHERUNGSSCHADENNR NVARCHAR(100) NULL,
        SFAEMAILVERSICHERUNG NVARCHAR(255) NULL,
        SFARECHNUNGAN NVARCHAR(100) NULL,
        SFAKASSE NVARCHAR(100) NULL,
        SFASONSTIGEKOSTEN DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SFAOFFENEFORDERUNG DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SFAKOSTENKOMPLETT BIT NOT NULL DEFAULT 0,
        SFABEARBEITER NVARCHAR(120) NULL,
        SFAWIEDERVORLAGEAM NVARCHAR(10) NULL,
        SFAERFORDERLICHEARBEITEN NVARCHAR(MAX) NULL,
        SFAERSTELLTVON NVARCHAR(100) NOT NULL,
        SFAERSTELLTAM DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        SFAAENDERUNGAM DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_DATSCHADENSFAELLE_SFANUMMER'
      AND object_id = OBJECT_ID('dbo.DATSCHADENSFAELLE')
)
BEGIN
    CREATE UNIQUE INDEX UX_DATSCHADENSFAELLE_SFANUMMER
        ON dbo.DATSCHADENSFAELLE (SFANUMMER);
END;
GO
